In [1]:
import pandas as pd
import numpy as np

In [24]:
ka2_df = pd.read_excel('../data/Erasmus-KA2-Mobility-Data.xlsx')

In [33]:
ka2_df['Mobility Year'] = ka2_df['Mobility Start Month'].str.split('-').str[0]
ka2_df['Mobility StartMonth'] = ka2_df['Mobility Start Month'].str.split('-').str[1]

In [34]:
ka2_df.head()

,Academic Year,Mobility Start Month,Mobility Duration,Activity (mob),Field of Education,Participant Country,Education Level,Participant Gender,Participant Profile,Special Needs,...,Sending City,Sending Organization,Receiving Country,Receiving City,Receiving Organization,Actual Participants (Contracted Projects),Year,Month,Mobility Year,Mobility StartMonth
0,-,2014-09,5,Short-term exchanges of groups of pupils,-,-,-,-,Learner,N,...,Freyburg,Sekundarschule Friedrich Ludwig Jahn Freyburg,ES - Spain,Ermua,Colegio San Pelayo,4,2014,09,2014,09
1,-,2014-09,5,Short-term exchanges of groups of pupils,-,-,-,-,Learner,N,...,Freyburg,Sekundarschule Friedrich Ludwig Jahn Freyburg,ES - Spain,Ermua,Colegio San Pelayo,2,2014,09,2014,09
2,-,2014-09,5,Short-term exchanges of groups of pupils,-,-,-,-,Learner,N,...,Freyburg,Sekundarschule Friedrich Ludwig Jahn Freyburg,ES - Spain,Ermua,Colegio San Pelayo,1,2014,09,2014,09
3,-,2015-02,5,Short-term exchanges of groups of pupils,-,-,-,-,Learner,N,...,Freistadt,Musik NMS Freistadt,DE - Germany,Freyburg,Sekundarschule Friedrich Ludwig Jahn Freyburg,5,2015,02,2015,02
4,-,2015-02,5,Short-term exchanges of groups of pupils,-,-,-,-,Learner,N,...,Freistadt,Musik NMS Freistadt,DE - Germany,Freyburg,Sekundarschule Friedrich Ludwig Jahn Freyburg,5,2015,02,2015,02

In [30]:
ka2_df['Activity (mob)'].value_counts()

Activity (mob)
Short-term exchanges of groups of pupils    125930
Short-term joint staff training events        9269
Blended mobility of school learners           3864
Long-term study mobility of pupils            1024
Blended mobility of VET learners                35
Name: count, dtype: int64

In [32]:
ka2_df['Participant Profile'].value_counts()

Participant Profile
Learner    140122
Name: count, dtype: int64

In [35]:
ka2_df['Education Level'].value_counts()

Education Level
-     140122
Name: count, dtype: int64

In [ ]:

ka2_df['Special Needs'].value_counts()

Special Needs
N    70169
-    68639
Y     1314
Name: count, dtype: int64

In [37]:
ka2_df['Fewer Opportunities'].value_counts()

Fewer Opportunities
N    68704
-    68639
Y     2779
Name: count, dtype: int64

In [29]:
# distribution of year 
year_counts = ka2_df['Year'].value_counts().sort_index()
print(year_counts)
print(sum(year_counts))

Year
2014      580
2015    11673
2016    16374
2017    17568
2018    19400
2019    21807
2020     7001
2021     9970
2022    27332
2023     8417
Name: count, dtype: int64
140122

In [8]:
# count missing values in each column
print(ka2_df.shape)
missing_values = ka2_df.isin(['-', '']).sum()
print(missing_values)

(140122, 20)
Academic Year                                140122
Mobility Start Month                              0
Mobility Duration                                 0
Activity (mob)                                    0
Field of Education                           140122
Participant Country                          140122
Education Level                                   0
Participant Gender                           140122
Participant Profile                               0
Special Needs                                 68639
Fewer Opportunities                           68639
Disadvantaged Background                      68639
Participant Age                              119393
Sending Country                                   0
Sending City                                  68639
Sending Organization                              0
Receiving Country                                 0
Receiving City                                68639
Receiving Organization                            0
Actual Participants (Contracted Projects)         0
dtype: int64

Completely empty columns:

-Academic Year
-Field of Education  
-Participant Country
-Participant Gender
-Participant Profile - all are learner
-Participant Age - 119393/140122 empty
-Education Level - all '-'

In [ ]:
ka2_df_cleaned = ka2_df[['Mobility Year', 'Mobility StartMonth', 'Activity (mob)', 'Special Needs', 'Fewer Opportunities', 'Disadvantaged Background', 'Sending Country', 'Sending Organization', 'Receiving Country', 'Receiving Organization', 'Actual Participants (Contracted Projects)']].copy()
ka2_df_cleaned = ka2_df_cleaned.replace('-', 'unknown')
ka2_df_cleaned = ka2_df_cleaned.replace('', 'unknown')

ka2_df_cleaned.head()

,Mobility Year,Mobility StartMonth,Activity (mob),Special Needs,Fewer Opportunities,Disadvantaged Background,Sending Country,Sending Organization,Receiving Country,Receiving Organization,Actual Participants (Contracted Projects)
0,2014,09,Short-term exchanges of groups of pupils,N,N,N,DE - Germany,Sekundarschule Friedrich Ludwig Jahn Freyburg,ES - Spain,Colegio San Pelayo,4
1,2014,09,Short-term exchanges of groups of pupils,N,N,N,DE - Germany,Sekundarschule Friedrich Ludwig Jahn Freyburg,ES - Spain,Colegio San Pelayo,2
2,2014,09,Short-term exchanges of groups of pupils,N,N,N,DE - Germany,Sekundarschule Friedrich Ludwig Jahn Freyburg,ES - Spain,Colegio San Pelayo,1
3,2015,02,Short-term exchanges of groups of pupils,N,N,N,AT - Austria,Musik NMS Freistadt,DE - Germany,Sekundarschule Friedrich Ludwig Jahn Freyburg,5
4,2015,02,Short-term exchanges of groups of pupils,N,N,N,AT - Austria,Musik NMS Freistadt,DE - Germany,Sekundarschule Friedrich Ludwig Jahn Freyburg,5

In [40]:
ka2_df_cleaned.to_csv('../data/ka2_mobility_data_cleaned.csv', index=False)

In [41]:
unique_orgs = pd.concat([ka2_df_cleaned['Sending Organization'], ka2_df_cleaned['Receiving Organization']]).unique()
print(f"Number of unique organizations: {len(unique_orgs)}")
unique_lower_orgs = [org.lower() for org in unique_orgs]
print(f"Number of unique organizations (case-insensitive): {len(set(unique_lower_orgs))}")

Number of unique organizations: 20109
Number of unique organizations (case-insensitive): 19941

In [42]:
ka2_df_cleaned['Sending Organization'] = ka2_df_cleaned['Sending Organization'].str.lower()
ka2_df_cleaned['Receiving Organization'] = ka2_df_cleaned['Receiving Organization'].str.lower()
ka2_df_cleaned.to_csv('../data/ka2_mobility_data_cleaned.csv', index=False)

In [9]:
unique_sending_countries = ka2_df['Sending Country'].unique()
unique_receiving_countries = ka2_df['Receiving Country'].unique()
print(f"Unique Sending Countries: {len(unique_sending_countries)}")
print(unique_sending_countries)
print(f"\nUnique Receiving Countries: {len(unique_receiving_countries)}")
print(unique_receiving_countries)

unique_countries = set(unique_sending_countries) | set(unique_receiving_countries)
print(f"\nUnique Countries (Sending and Receiving): {len(unique_countries)}")
print(unique_countries)

Unique Sending Countries: 39
<StringArray>
[                        'DE - Germany',
                         'AT - Austria',
                           'ES - Spain',
                        'SK - Slovakia',
                         'HU - Hungary',
                         'HR - Croatia',
                        'BG - Bulgaria',
                         'CZ - Czechia',
                         'RO - Romania',
                        'SI - Slovenia',
                        'PT - Portugal',
                           'IT - Italy',
                          'TR - Turkey',
                         'BE - Belgium',
                         'FI - Finland',
                          'SE - Sweden',
                       'LT - Lithuania',
                          'PL - Poland',
                  'UK - United Kingdom',
                         'IE - Ireland',
                         'DK - Denmark',
                         'EE - Estonia',
                          'LV - Latvia',
                          'NO - Norway',
                          'CY - Cyprus',
                          'FR - France',
                     'NL - Netherlands',
                         'IS - Iceland',
                           'MT - Malta',
                          'EL - Greece',
                      'LU - Luxembourg',
                   'LI - Liechtenstein',
 'MK - The Republic of North Macedonia',
                      'ME - Montenegro',
          'BA - Bosnia and Herzegovina',
          'XK - Kosovo * UN resolution',
                           'LY - Libya',
                         'GE - Georgia',
                          'RS - Serbia']
Length: 39, dtype: str

Unique Receiving Countries: 34
<StringArray>
[                          'ES - Spain',
                         'DE - Germany',
                         'HU - Hungary',
                        'SK - Slovakia',
                         'AT - Austria',
                         'HR - Croatia',
                        'SI - Slovenia',
                         'RO - Romania',
                         'CZ - Czechia',
                        'BG - Bulgaria',
                        'PT - Portugal',
                          'TR - Turkey',
                           'IT - Italy',
                         'BE - Belgium',
                         'FI - Finland',
                       'LT - Lithuania',
                          'SE - Sweden',
                          'PL - Poland',
                  'UK - United Kingdom',
                         'IE - Ireland',
                          'NO - Norway',
                          'EL - Greece',
                         'DK - Denmark',
                          'LV - Latvia',
                         'EE - Estonia',
                          'CY - Cyprus',
                          'FR - France',
                           'MT - Malta',
                         'IS - Iceland',
                     'NL - Netherlands',
 'MK - The Republic of North Macedonia',
                   'LI - Liechtenstein',
                      'LU - Luxembourg',
                          'RS - Serbia']
Length: 34, dtype: str

Unique Countries (Sending and Receiving): 39
{'GE - Georgia', 'LU - Luxembourg', 'RO - Romania', 'PT - Portugal', 'SE - Sweden', 'NO - Norway', 'UK - United Kingdom', 'AT - Austria', 'CY - Cyprus', 'SI - Slovenia', 'FI - Finland', 'BE - Belgium', 'MT - Malta', 'BA - Bosnia and Herzegovina', 'BG - Bulgaria', 'LV - Latvia', 'RS - Serbia', 'SK - Slovakia', 'FR - France', 'HR - Croatia', 'TR - Turkey', 'EL - Greece', 'MK - The Republic of North Macedonia', 'ME - Montenegro', 'IT - Italy', 'DE - Germany', 'IS - Iceland', 'HU - Hungary', 'XK - Kosovo * UN resolution', 'LY - Libya', 'IE - Ireland', 'NL - Netherlands', 'LT - Lithuania', 'EE - Estonia', 'CZ - Czechia', 'ES - Spain', 'DK - Denmark', 'PL - Poland', 'LI - Liechtenstein'}

In [ ]:
# extra_data = pd.read_csv('../data/country_extra_data.csv')
# print(extra_data.head())
# extra_data['Geographical_Region'] = ['none'] * len(extra_data)
# print(extra_data.head())
# extra_data.to_csv('../data/country_extra_data.csv', index=False)

           Country Language_Family Economic_Family
0     GE - Georgia              14            none
1  LU - Luxembourg           1,3,4            none
2     RO - Romania               4            none
3    PT - Portugal               4            none
4      SE - Sweden             1,2            none
           Country Language_Family Economic_Family Geographical_Region
0     GE - Georgia              14            none                none
1  LU - Luxembourg           1,3,4            none                none
2     RO - Romania               4            none                none
3    PT - Portugal               4            none                none
4      SE - Sweden             1,2            none                none